--- 
services: 
  emby: 
    container_name: emby
    environment: 
      - PUID=1001
      - PGID=100
      - TZ=US/Eastern
      - UNMASK=022
    image: "linuxserver/emby"
    network_mode: bridge
    ports: 
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped
    volumes:
      - path/to/disk/Data/Config:/config 
      - path/to/disk/Data/Movies:/data/movies 
      - path/to/disk/Data/Photos:/data/photos
      - path/to/disk/Data/Atmos:/data/atmos
      - path/to/disk/Data/MixedContent:/data/mixedcontent
      - path/to/disk/Animated:/data/animated
version: "2.3"
